### ISSUE TITLE
Broken Link Anchors and Navigation for Headline Links

### ISSUE THREAD

**Issue by PhasecoreX** [jpanther/congo#111]
### What happened?

Specifically, if the headline is a link, it breaks the generation of the link anchor and right side navigation.
Here is a page that reproduces it, just place it in `/content/test.md` so that Hugo doesn't complain about the first link:
```
---
date: 2022-02-11
title: Test
---

## [Test Page]({{< ref "/test" >}})

Headlines that link to another page on the blog have a messed up anchor with a "HAHA HUGO SHORTCODE" thing in them. The navigation on the right doesn't work for these.

## [Github](https://github.com/)

Links to other websites do generate an anchor, but also append the url to these anchors (might be intentional?). However the navigation on the right doesn't work, and instead links directly to the other website.

### [Smaller Github](https://github.com/)

From what I can tell, it's just the anchor name is being generated with the link included. The "HAHA HUGO SHORTCODE" turns into the appropriate link once you try typing it out in the content. Might be why the right navigation lists out URLs as their links, and then the inter blog one shows the shortcode. I assume we don't want this?

#### [Smallest Github](https://github.com/)

Or if we do want it, the navigation links on the right need to link to these anchors, not be broken or navigate to the URLs themselves.

```

### Theme version

v2.0.4

### Hugo version

v0.92.1

### What browsers are you seeing the problem on?

Firefox

**Comment by jpanther** [comment]
Unfortunately this is due to limitations in the TOC generation in Hugo.

With regards to the links in headings taking precedence over the anchor links, the theme only calls the default Hugo `{{ .TableOfContents }}` method and so there's no way to easily adjust this behaviour. Ideally these links should be stripped out of the TOC output.

See https://github.com/gohugoio/hugo/issues/7158 and https://github.com/gohugoio/hugo/issues/7557.

As for the shortcode "HAHA HUGO SHORTCODE" issue, this can be avoided by using the `{{% shortcode %}}` syntax which will process the shortcode before rendering the output. In your example, substitute the heading for `## [Test Page]({{% ref "/test" %}})` and this will avoid this issue, although will then still exhibit the linking behaviour described above.

See https://github.com/gohugoio/hugo/issues/6081.

In the meantime the workaround is to either not include links in headings or disable the TOC for the page where you need these links. In the future I might have to look at other ways to generate the TOC but decided that using the built in Hugo method is the cleanest for now.

**Comment by PhasecoreX** [comment]
Thank you for those references! I am new to Hugo so I haven't figured out some of the intricacies on how the pages are rendered yet. I'll switch my page to use the `{{% shortcode %}}` syntax in the headers, then at least all of my table of contents will just be links to the pages I was linking to. It's just a jump page to my other projects.

I don't think you need to reimplement a whole TOC if this built in one is working 99% correctly. I think it should be fixed upstream. But, if you do want to, feel free to re-open this issue. Regardless I am already watching the aforementioned Hugo issues too.

Thanks again!
