### ISSUE TITLE
Icon in headings break TOC

### ISSUE THREAD

**Issue by OCram85** [jpanther/congo#133]
### What happened?

If you use the icon shortcode in headings they doesn't show up correct in the TOC

```
{{< icon "address-card" >}} Hi, my name is Marco Blessing and I live in the south of Germany near a city called
[Karlsruhe](https://goo.gl/maps/kDpo6bb9V2r).
```

![image](https://user-images.githubusercontent.com/13993700/155276455-ca7e3998-fd2f-4e36-8d35-7a0e0a83fce0.png)

### Theme version

2.0.5

### Hugo version

v0.91.0++

### What browsers are you seeing the problem on?

Chrome

**Comment by jpanther** [comment]
Unfortunately this is a known issue in Hugo and not something related to the theme. See https://github.com/gohugoio/hugo/issues/6081 for more details, but a workaround seems to be to use `{{% %}}` syntax when including the shortcode. This will then tell Hugo to process the shortcode before rendering it in the table of contents.

**Comment by OCram85** [comment]
wow didn't know that issue. Unfortunately this doesn't help. It seems like its now splitting the heading and adds the text as an `p` element. And the toc element is missing now:

![image](https://user-images.githubusercontent.com/13993700/155470634-b841e923-1d30-4374-913f-f0a00790aa09.png)
![chrome_kuUU0YFts1](https://user-images.githubusercontent.com/13993700/155471070-bc83c29c-a088-4bd6-a68e-0b7a3a75ca8b.png)
![chrome_oJ6xNCIEAB](https://user-images.githubusercontent.com/13993700/155471090-faca8aed-1b5a-48cf-baea-f755eddf6b0c.png)

Well I guess we have to wait until it's fixed within hugo itself. I hoped, I could avoid using emojis here :(

**Comment by jpanther** [comment]
I've had another look at this to see if I can improve the output so it doesn't split the heading but there doesn't seem to be a way to get it to work.

If you really need icons in the headings, you might be better off looking at including the SVG in the heading manually, or working around it by including FontAwesome directly in your project. Alternatively, you could add custom CSS to inject the icons but then you'd have to style the headings using HTML rather than Markdown.

**Comment by OCram85** [comment]
Thanks for you help. I guess this issue can be closed - because it's rooted in hugo itself, rather than the congo theme.
