### ISSUE TITLE
Responsive text with tailwind typography

### ISSUE THREAD

**Issue by laywens** [jpanther/congo#184]
### What happened?

Hi, I understand from the tailwind typography docs that [type scale can be modified for responsive breakpoints](https://tailwindcss.com/docs/typography-plugin#applying-a-type-scale). Yet, when I use this syntax with your your theme, I can't seem to get the body text to render at any scale other than `1rem` (using `prose-lg` or `lg:prose-xl` inline has no effect).

Is there an override in the stylesheets preventing this change of scale?

I've looked and I can't figure it out.

Btw spectacular job with the theme!

### Theme version

2.1.3

### Hugo version

v0.97.2+extended

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by jpanther** [comment]
Hi @shanewasley, this is actually the expected behaviour as the compiled stylesheet in the theme only includes the Tailwind classes necessary for the theme to function. In order to add extra classes like the `prose` ones you mention, you will need to recompile the stylesheet. Follow the instructions in the [Building the theme CSS from source](https://jpanther.github.io/congo/docs/advanced-customisation/#building-the-theme-css-from-source) documentation for more details.

If you wanted a less complex solution for simply scaling the text size, you can use a custom CSS file. The theme documentation has details for this too - [Adjusting the font size](https://jpanther.github.io/congo/docs/advanced-customisation/#adjusting-the-font-size). You could, for instance, include your own `@media` break points to scale the size for various viewports.

**Comment by swaynehales** [comment]
Got it. I didn't understand how the compiling worked and what was included and excluded from the build. But I went back over your awesome documentation and realized you already explained this. And thanks for including the compiler command!

PS, I just used a simple media breakpoint to solve my issue.
