### ISSUE TITLE
Navigation menu is misaligned in the mobile browser

### ISSUE THREAD

**Issue by ghost** [jpanther/congo#399]
### What happened?

The layout parameter in params.toml is set to hybrid, the navigation menu is misaligned in the mobile browser, 

![iOS-Safari](https://user-images.githubusercontent.com/108618588/205478715-5e442636-a1be-41e1-9006-630d3ab17e2f.jpg)

However, there is no problem in the "development tools" mode of the desktop browser, thanks.

![chrome-dt](https://user-images.githubusercontent.com/108618588/205478718-bc5a520a-f4bd-4897-bb0f-cab555f0c45a.jpg)

### Theme version

v2.4.2

### Hugo version

v0.107.0

### What browsers are you seeing the problem on?

Chrome, Safari

### Relevant Hugo log output

```shell
No response
```

**Comment by AntoineSoetewey** [comment]
I believe this issue shouldn't be marked as stale as it is still present.

**Comment by Nicceboy** [comment]
The problem seems to be indeed related to specific browsers. 
Even thought Firefox on iOS uses Safari  for rendering, it works fine. But not in the Safari itself.

Edit: Might be related to changed height, caused bottom navigation on iOS safari (where url is located, for example). Navigation seems to fix itself if you scroll down, and Safari hides the bottom bar.

**Comment by jpanther** [comment]
Thanks for the report. Apologies for my delayed response, I've been super busy! The alignment of things like this is a constant battle because of the way Safari calculates the viewport size and as @Nicceboy suggests, it is probably due to the bottom navigation. I'll have a look into it when I have a moment and see if I can track it down.

**Comment by leonidboykov** [comment]
Same issue with Chrome on Android.
