### ISSUE TITLE
Language toggle is not consistent

### ISSUE THREAD

**Issue by AntoineSoetewey** [jpanther/congo#574]
### What happened?

Hello,

In v2.6.1 the language toggle is not consistent: for one language it's the flag, and when I switch to the other language, it's the country code. 

See it in video:

https://github.com/jpanther/congo/assets/17910063/83fb3b8a-f1cf-4450-9df5-dde5c1f8e941

Here is my repo in case it helps: https://github.com/AntoineSoetewey/antoinesoetewey.com (since then, I restored to v2.5.4 to prevent this issue).

### Theme version

v2.6.1

### Hugo version

I don't know

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by AntoineSoetewey** [comment]
Dear @jpanther,

I guessed you might be busy at the moment. By any chance, do you have any thoughts to share on this issue?

**Comment by jpanther** [comment]
I'm quickly editing this because I feel like I'm going on a real tangent trying to put all the i18n changes into this issue! I think the issue you're having here is because the languages config structure is different when using newer Hugo versions. You need to reformat the file so that the `displayName` is under `[params]` as per the file that ships with the theme. Unfortunately this change is out of my hands and is a new Hugo paradigm that users have to adjust to.

**Comment by AntoineSoetewey** [comment]
Thanks, this indeed fix the issue !
