### ISSUE TITLE
Feature image not in .Content

### ISSUE THREAD

**Issue by jukremer** [jpanther/congo#610]
### Issue description

I customized my RSS feed to include `.Content` instead of `.Description`.

I noticed when using `feature` images that they don't end up in the feed. 
My workaround is the set the image as a Markdown image and as thumbnail. 

Is this behavior intended?

### Theme version

v2.6.1

### Hugo version

hugo v0.115.3+extended darwin/amd64 BuildDate=unknown

**Comment by jpanther** [comment]
This is something I haven't previously considered, so it's working as intended, but it could definitely be improved. I might have to look into including the featured image in the RSS feed.

**Comment by jpanther** [comment]
I've done a bit more digging into this and if you are going to use `.Content` in your RSS feed then there's no way to include the feature image. This is because the `.Content` parameter is immutable. Perhaps the workaround for this would be to add some logic to your RSS template to include the feature image before the content if one exists.
