### ISSUE TITLE
Large empty space between title and content in `single` layout without page meta

### ISSUE THREAD

**Issue by ohueter** [jpanther/congo#611]
### Issue description

There is a large empty space between the title and content in the `single` layout when no page meta is displayed, as can be seen in the attached screenshot (the page title is hidden behind the Devtools popup). It's shifting all content towards the bottom, including the `lead` partial, which IMO should be placed directly below the title.

<img width="1313" alt="single" src="https://github.com/jpanther/congo/assets/57348167/1ec50722-89f9-4b15-8887-73333105b7f7">

It's caused by this block:
https://github.com/jpanther/congo/blob/60fc10dfb1c2b6882af193fe7e2f0c205a9adddd/layouts/_default/single.html#L13-L15

I'm aware of methods to override the layout locally, but I'm wondering if this behavior is intentional? Maybe this `div` block shouldn't be rendered at all if no meta is displayed?

### Theme version

v2.6.1

### Hugo version

hugo v0.114.1+extended darwin/arm64

### Which browser rendering engines are you seeing the problem on?

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, Opera, etc.)

**Comment by ohueter** [comment]
@jpanther If you agree I'd go ahead and try to create a PR with a fix?

**Comment by jpanther** [comment]
Apologies for taking so long to respond to this issue, @ohueter. This behaviour is intentional as the empty div maintains the spacing between the page title and main content. The correct spacing should be as per this screenshot when there's no metadata visible...

![Screenshot 2023-10-25 at 11 55 10](https://github.com/jpanther/congo/assets/4462786/b39aab90-fd1d-4941-bd44-27fe5cd442c7)

If this is not the behaviour you're looking for, perhaps the [`simple`](https://jpanther.github.io/congo/docs/content-examples/#simple-pages) page layout is an alternative? Otherwise, [overriding](https://jpanther.github.io/congo/docs/content-examples/#overriding-default-layouts) the `single.html` layout is your best option.

**Comment by jpanther** [comment]
I'm going to close this issue as I don't believe any changes are required at this point in time.
