### ISSUE TITLE
Problem when creating new site from RStudio with blogdown R package

### ISSUE THREAD

**Issue by AntoineSoetewey** [jpanther/congo#656]
### Issue description

Hello,

I am trying to create a new site within RStudio with the blogdown R package.

Following [this recommended workflow](https://bookdown.org/yihui/blogdown/workflow.html), I used to create new sites with `blogdown::new_site(theme = 'jpanther/congo')`. It worked fine in the past as I have used this command for several of my sites.

For a new site I'm trying to build, this command doesn't work anymore.

Here is the output of the error:

<img width="1624" alt="Screenshot 2023-09-20 at 12 19 30" src="https://github.com/jpanther/congo/assets/17910063/5289c410-ed49-45c7-978d-01ee9e07ebc6">

It seems that the function "page" is not defined, but I don't know how to define it (and I never needed to define it in the past). Am I missing something?

Thanks in advance for your help!

Regards,
Antoine

### Theme version

v2.6.1

### Hugo version

0.91.2

**Comment by eliezerb** [comment]
Hey, @AntoineSoetewey, I had some free time today and tried to reproduce your problem here! You could try to update Hugo and see if that is the case. Otherwise, let me know if you have something else you want me to try :)

## Setup

- Windows 11 x64
- RStudio 2023.06.02 - Build 561
- Theme version v2.6.1
- blogdown::hugo_version() - ‘0.118.2’

## Steps

- Made a clean install of R and RStudio
- setwd("C:/Users/user/empty-folder")
- install.packages("blogdown")
- blogdown::new_site(theme = 'jpanther/congo')

## Results

The web server ran normally, with the sample Markdown post working on the web application.

![image](https://github.com/jpanther/congo/assets/2414408/03bb8053-48fa-455f-ac6a-e62c7641ddaa)

**Comment by micah-svenson** [comment]
I had the same error show up when trying to run the congo example site just now. 
Upgrading Hugo solved the issue for me. I went from Hugo 0.104.3 -> 0.118.2

**Comment by AntoineSoetewey** [comment]
Upgrading Hugo solved the issue for me too. Thanks for your help!
