### ISSUE TITLE
The thumbnail images, or cover images are not showing

### ISSUE THREAD

**Issue by Trat1100** [jpanther/congo#836]
### Issue description

I am trying to get the thumbnail or cover images in the lists section of posts, but it's not working. This is my posts folder:
```
posts
    ├── Authelia-with-npm
    │   ├── Authelia-with-npm.md
    │   └── featured.jpg
    ├── Baserow-no-code-database
    │   ├── Baserow-No-Code-Database.md
    │   └── fature.jpg
    ├── Harden-linux-server-security
    │   ├── Harden-Linux-Server-Security.md
    │   └── thumb.jpg
    └── _index.md
   ```
   As you can see I tried `thumb`, `feature` and also `featured` in jpg names but none appears on website. And yeah, Breadcrumbs are enabled. The site is being hosted on my ubuntu machine and I tried using both github and hugo module for theme installation (as written in docs). The example site is: https;//trat.tech/posts

### Theme version

v2.8.1

### Hugo version

hugo v0.124.0-629f84e8edfb0b1b743c3942cd039da1d99812b0

### URL to sample repository or website

https;//trat.tech

**Comment by jpanther** [comment]
This is because you have not created page bundles and have instead opted for single content pages. You need to name your individual posts `index.md` in order to create the bundle that the theme uses to locate these image resources.

Hugo docs: [Page Resources](https://gohugo.io/content-management/page-resources/) & [Page Bundles](https://gohugo.io/content-management/page-bundles/)

**Comment by Trat1100** [comment]
Oh, Alright. My bad I got it now.
