### ISSUE TITLE
Articles with `externalUrl` accesible through the navigation links

### ISSUE THREAD

**Issue by cbelena** [jpanther/congo#92]
### What happened?

Hi @jpanther, as I commented on #88, if an article has `externalUrl` set, you can access the content of the 'article' through the navigation links.

### What is expected to happen
I think there is two choices:

1. Change the `href` of the navigation link to point to the `externalUrl`, instead to the page of the article.
2. Skip the previous or next article(s) that have `externalUrl` set until previous or next article without it. This way, the navigation is not "disrupted", and articles with `externalUrl` are only accesible from article listings.

I have a working little fix for the first option, so I can submit a PR. But if you prefer the second option, I think that I'm not ready for it... yet! 😀 I'm a begginer in Hugo, and with HTML/CSS in general.

I believe the second option is better, but I'm not sure. What do you think? Maybe start with option 1 to fix the issue and then option 2 as a future improvement?

Thank you!

### Theme version

v1.6.4

### Hugo version

v0.92

**Comment by jpanther** [comment]
I agree that option 1 isn't the best because it has a poor UX and it renders the article pagination almost pointless. The thing is this isn't really an issue that needs solving if the content is created properly. I've just been doing some testing and I think this feature is actually working as I originally intended.

`externalUrl` is one feature that I added right at the very beginning of the theme because I wanted it for my own website and so it's not particularly well documented. Really what is meant to happen is that you also set special `_build` parameters in the front matter of the page too.

```yaml
title: "An External Article"
externalUrl: "http://github.com/"
_build:
    render: false
    list: local
```

This tells Hugo not to output a page for that article and will prevent the problem of being able to link to a page that serves no purpose.

The real issue is I don't know if there's a way I can programatically set the `_build` flags whenever `externalUrl` is set. Perhaps the best workaround is to create a new archetype for this content type and better document how this should work.

If you try this on your website does the feature then behave as you would expect?

**Comment by cbelena** [comment]
Oh, that's very interesting! I didn't know about [these special parameters](https://gohugo.io/content-management/build-options/). Indeed, with that extra front matter it behaves exactly like I was thinking in option 2! 🎉 

So the only issue here is the lack of these details in the docs. I'm going to close this issue, then. Thank you very much again! 😀

**Comment by jpanther** [comment]
This will now be in the docs in the next version!
